#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

if (is_file(__DIR__ . '/common/config/local.php')) {
    $localConfig = include(__DIR__ . '/common/config/local.php');
} else {
    $localConfig = [];
}

try {
    require(__DIR__ . '/vendor/autoload.php');
    require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
    require(__DIR__ . '/common/config/bootstrap.php');
    require(__DIR__ . '/console/config/bootstrap.php');

    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/common/config/main.php'),
        $localConfig,
        require(__DIR__ . '/console/config/main.php')
    );
} catch (Sil\PhpEnv\EnvVarNotFoundException $e) {
    fwrite(STDERR, $e->getMessage() . PHP_EOL);
    
    openlog('pw-api', LOG_NDELAY | LOG_PERROR, LOG_USER);
    syslog(LOG_CRIT, $e->getMessage());
    closelog();
    
    exit(1);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
