<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth.MissingClientID' => '클라이언트 ID가 없습니다.',
    'Google.EmployeeIdNotFound' => 'Employee ID not found in G Suite',
    'Google.MultipleEmailsFound' => 'Multiple email addresses found in G Suite. Cannot resolve.',
    'Method.AlreadyExists' => '복구 방법이 이미 있습니다.',
    'Method.CodeExpired' => '만료 된 인증 코드',
    'Method.CodeMissing' => '코드가 필요합니다.',
    'Method.EmailReuseError' => '보조 이메일 복구 방법으로 제공되는 기본 이메일 주소입니다.',
    'Method.InvalidCode' => '잘못된 검증 코드',
    'Method.InvalidEmail' => '유효하지 않은 이메일 주소',
    'Method.MissingValue' => '값이 필요합니다',
    'Method.NotFound' => '복구 방법을 찾을 수 없습니다.',
    'Method.PersonnelError' => '인사 기록 찾기 오류',
    'Method.TooManyFailures' => '이 복구 방법에 너무 많은 실패가 있습니다.',
    'Mfa.AlreadyExists' => '이 2SV는 이미 존재합니다.',
    'Mfa.InvalidCode' => 'Invalid data provided',
    'Mfa.MissingValue' => '값이 필요합니다',
    'Mfa.RateLimitFailure' => 'MFA 비율 한도 실패',
    'Mfa.RecordNotFound' => '레코드를 찾을 수 없습니다',
    'Mfa.TypeMissing' => '종류를 입력하십시오',
    'Mfa.UpdateFailure' => '업데이트 실패',
    'Mfa.VerifyFailure' => 'MFA 확인 실패',
    'Multiple.SetPartialSuccess {successes} {errors}' => '{successes} 에서 비밀번호를 설정했지만 {errors} 에서 비밀번호를 설정하지 못했습니다.',
    'Multiple.SetFailed {errors}' => '비밀번호를 {errors} 으로 설정하지 못했습니다.',
    'Password.Breached' => '입력 한 비밀번호는 이전에 다른 웹 사이트의 데이터 유출로 발견되었습니다. 귀하의 계좌가 손상되었을 수도 있고 아닐 수도 있습니다. 여기에 다른 암호를 사용하고 방문하시기 바랍니다 <a href="https://idphelp.sil.org/logging-in/password/password-recommendations#h.p_LOkQcA18P0qs" target="_blank">이 도움말 페이지</a> 자세한 내용은.',
    'Password.DisallowedContent' => '귀하의 비밀번호는 다음을 포함하지 않을 수 있습니다 : {labelList} (코드 180)',
    'Password.MissingPassword' => '비밀번호가 필요합니다.',
    'Password.PasswordReuse' => '비밀번호를 업데이트 할 수 없습니다. 이 암호를 사용하기 전에 다른 것을 사용하십시오.',
    'Password.PublicPasswordUsed' => '하하, 좋은 분. 아니요, 좋은 비밀번호를 만드는 방법에 대한 동영상에서 본 비밀번호를 사용해서는 안됩니다.',
    'Password.TooLong' => '암호가 최대 길이 인 {maxLength} (코드 110)을 초과합니다.',
    'Password.TooShort' => '암호가 최대 길이 인 {minLength} (코드 100)을 초과합니다.',
    'Password.TooWeak' => '암호가 최대 길이 인 {minScore} (코드 150)을 초과합니다.',
    'Password.UnknownProblem' => '자막을 검색하는 동안 오류가 발생했습니다. 다시 시도하십시오. 문제가 지속되면 지원팀에 문의하시기 바랍니다.',
    'Password.UpdateError' => '비밀번호를 업데이트 할 수 없습니다. 잠시 후 다시 시도하십시오. 문제가 계속되면 지원팀에 문의하십시오.',
    'Password.UpdateFailure' => '비밀번호를 업데이트 할 수 없습니다. 지원부에 문의하십시오.',
    'Reset.AccountLocked' => '비밀번호 재설정이 불가능합니다. 계정이 잠겼습니다.',
    'Reset.CannotEnable' => '재설정을 활성화 할 수 없습니다.',
    'Reset.CreateFailure' => '새로운 lua state를 생성할 수 없습니다.',
    'Reset.IncrementAttemptsError' => '시도 횟수를 늘릴 수 없습니다.',
    'Reset.InvalidCode' => '잘못된 검증 코드',
    'Reset.MissingClientID' => '누락 된 클라이언트 ID',
    'Reset.MissingCode' => '코드가 필요합니다.',
    'Reset.MissingMethodUID' => '메소드 유형 재설정에 필요한 메소드 UID',
    'Reset.MissingRecaptchaCode' => 'reCAPTCHA 인증 코드가 필요합니다.',
    'Reset.MissingResetType' => '잘못된 요청 유형입니다',
    'Reset.MissingUsername' => '값이 필요합니다',
    'Reset.NotFound' => '파일을 찾을 수 없음',
    'Reset.PasswordResetForSubject' => '{idpDisplayName} 비밀번호 재설정 요청 {name}',
    'Reset.PasswordResetSubject' => '{idpDisplayName} 비밀번호 재설정 요청',
    'Reset.RecaptchaFailedVerification' => 'reCAPTCHA가 확인에 실패했습니다.',
    'Reset.SetDisableTimeError' => 'disable_until을 사용하여 재설정을 저장할 수 없습니다.',
    'Reset.UnknownType' => '알 수없는 재설정 유형이 요청되었습니다.',
    'Reset.UpdateFailure' => '데이터베이스에서 재설정을 업데이트 할 수 없습니다. 이메일이 전송되지 않았습니다.',
    'Reset.UpdateTypeError' => '설정을 업데이트할 수 없습니다.',
    'Reset.UserNotFound' => '사용자를 찾지 못했습니다',
    'Utils.InvalidEmail' => '유효하지 않은 이메일 주소',
    'Utils.RecaptchaVerifyFailure' => 'reCAPTCHA를 확인할 수 없습니다.',
    'Zxcvbn.LowScore' => '암호가 최소 강도 {minScore}충족시키지 못했습니다. 일부 단어를 추가하고 일반적인 문구는 피하십시오.',
];
