<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '접근 토큰',
    'Access Token Expiration' => '액세스 토큰 만료',
    'Attempts' => '시도',
    'Auth Type' => '인증 유형',
    'Code' => '코드',
    'Created' => 'Created',
    'Deleted At' => '삭제됨',
    'Details' => 'Details',
    'Disable Until' => '최대 사용 중지',
    'Email' => '이메일',
    'Employee ID' => '직원 식별',
    'Expires' => '만료',
    'First Name' => '이름',
    'Hide' => '숨기기',
    'ID' => '아이디',
    'Idp Username' => 'IdP 사용자 이름',
    'Last Name' => '성',
    'Topic' => '주제',
    'Type' => '유형',
    'Uid' => 'UID',
    'User ID' => '사용자 아이디',
    'Uuid' => 'UUID',
    'Value' => '환율',
    'Verification Attempts' => '확인 시도',
    'Verification Code' => '인증 코드',
    'Verification Expires' => '확인 실패',
    'Verified' => '확인',
];
