<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Token de acceso',
    'Access Token Expiration' => 'Caducidad del token de acceso',
    'Attempts' => 'Intentos',
    'Auth Type' => 'Tipo de autorización',
    'Code' => 'Código',
    'Created' => 'Creado',
    'Deleted At' => 'Eliminado',
    'Details' => 'Detalles',
    'Disable Until' => 'Visible hasta',
    'Email' => 'Correo electrónico',
    'Employee ID' => 'Identificador de empleado',
    'Expires' => 'Caducidad',
    'First Name' => 'Nombre',
    'Hide' => 'Esconder',
    'ID' => 'ID',
    'Idp Username' => 'Nombre de usuario de IdP',
    'Last Name' => 'Cognome',
    'Topic' => 'Asunto',
    'Type' => 'Tipo',
    'Uid' => 'UID',
    'User ID' => 'ID de usuario',
    'Uuid' => 'UUID',
    'Value' => 'Valor',
    'Verification Attempts' => 'Cuestiones de verificación',
    'Verification Code' => 'Codigo de Verificacion',
    'Verification Expires' => 'La verificación ha fallado',
    'Verified' => 'Verificado',
];
