<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Access Token',
    'Access Token Expiration' => 'Access Token Expiration',
    'Attempts' => 'Attempts',
    'Auth Type' => 'Auth Type',
    'Code' => 'Code',
    'Created' => 'Created',
    'Deleted At' => 'Deleted At',
    'Details' => 'Details',
    'Disable Until' => 'Disable Until',
    'Email' => 'Email',
    'Employee ID' => 'Employee ID',
    'Expires' => 'Expires',
    'First Name' => 'First Name',
    'Hide' => 'Hide',
    'ID' => 'ID',
    'Idp Username' => 'IdP Username',
    'Last Name' => 'Last Name',
    'Topic' => 'Topic',
    'Type' => 'Type',
    'Uid' => 'UID',
    'User ID' => 'User ID',
    'Uuid' => 'UUID',
    'Value' => 'Value',
    'Verification Attempts' => 'Verification Attempts',
    'Verification Code' => 'Verification Code',
    'Verification Expires' => 'Verification Expires',
    'Verified' => 'Verified',
];
