<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'et',
    'Auth.MissingClientID' => 'Client ID est manquant',
    'Google.EmployeeIdNotFound' => 'ID de l\'employé non trouvé dans la Google Workspace',
    'Google.MultipleEmailsFound' => 'Plusieurs adresses e-mail trouvées dans Google Workspace. Impossible à résoudre.',
    'Method.AlreadyExists' => 'La méthode de récupération existe déjà',
    'Method.CodeExpired' => 'Code de vérification invalide',
    'Method.CodeMissing' => 'Code est requis',
    'Method.EmailReuseError' => 'Adresse électronique principale fournie comme autre méthode de récupération.',
    'Method.InvalidCode' => 'Code de vérification invalide',
    'Method.InvalidEmail' => 'Adresse email invalide fournie',
    'Method.MissingValue' => 'Valeur est requise',
    'Method.NotFound' => 'Méthode de récupération non trouvée',
    'Method.PersonnelError' => 'Erreur de localisation du dossier personnel',
    'Method.TooManyFailures' => 'Trop d\'échecs pour cette méthode de récupération',
    'Mfa.AlreadyExists' => 'Cette 2SV existe déjà',
    'Mfa.InvalidCode' => 'Code invalide fourni',
    'Mfa.MissingValue' => 'Valeur est requise',
    'Mfa.RateLimitFailure' => 'Échec de limite de taux MFA',
    'Mfa.RecordNotFound' => 'Enregistrement MFA non trouvé',
    'Mfa.TypeMissing' => '\'Type\' est requis',
    'Mfa.UpdateFailure' => 'Echec de la mise à jour MFA',
    'Mfa.VerifyFailure' => 'MFA vérifier l\'échec',
    'Multiple.SetPartialSuccess' => 'Le mot de passe a été bien défini sur {successes}, mais pas sur {errors}. Contactez {supportName} à {supportEmail} pour obtenir de l\'aide.',
    'Multiple.SetFailed' => 'Impossible de définir le mot de passe sur {errors}. Contactez {supportName} à {supportEmail} pour obtenir de l\'aide.',
    'Password.AlphaAndNumericRequired' => 'Votre mot de passe doit inclure à la fois une lettre et un chiffre.',
    'Password.Breached' => 'Le mot de passe que vous avez entré a déjà été découvert dans une violation de données d\'un site Web différent. Votre compte a peut-être été compromis ou non. Veuillez utiliser un mot de passe différent ici, puis visitez <a href="https://sites.google.com/sil.org/identityaccounts/logging-in/password-recommendations" target="_blank">cette page d’aide</a> pour en savoir plus.',
    'Password.ContainsBadByte' => 'Le mot de passe contient un caractère non autorisé',
    'Password.DisallowedContent' => 'Votre mot de passe ne peut contenir aucun de ceux-ci: {labelList} (code 180)',
    'Password.MissingPassword' => 'Mot de passe requis',
    'Password.PasswordReuse' => 'Impossible de mettre à jour le mot de passe. Si ce mot de passe a déjà été utilisé, veuillez utiliser quelque chose de différent.',
    'Password.PublicPasswordUsed' => 'Ha ha, bon. Non, vous ne devriez pas utiliser un mot de passe que vous avez vu dans une vidéo pour créer de bons mots de passe.',
    'Password.TooLong' => 'Votre mot de passe dépasse la longueur maximale de {maxLength} (code 110)',
    'Password.TooShort' => 'Votre mot de passe ne respecte pas la longueur minimale de {minLength} (code 100)',
    'Password.TooWeak' => 'Votre mot de passe ne répond pas à la force minimale de {minScore} (code 150)',
    'Password.UnknownProblem' => 'Il y a eu une erreur dans la recherche de sous-titres, veuillez réessayer. Si le problème persiste, veuillez contacter le support technique.',
    'Password.UpdateError' => 'Impossible de mettre à jour le mot de passe, attendez une minute, puis réessayez. Si ce problème persiste, veuillez contacter le support.',
    'Password.UpdateFailure' => 'Impossible de mettre à jour le mot de passe. S\'il vous plaît contacter le support.',
    'Reset.AccountLocked' => 'La réinitialisation du mot de passe n\'est pas possible. Le compte est verrouillé.',
    'Reset.CannotEnable' => 'Impossible d\'activer la réinitialisation.',
    'Reset.CreateFailure' => 'Impossible de créer une nouvelle réinitialisation',
    'Reset.IncrementAttemptsError' => 'Impossible d\'incrémenter les tentatives comptent.',
    'Reset.InvalidCode' => 'Code de vérification invalide',
    'Reset.MissingClientID' => 'ID client manquant',
    'Reset.MissingCode' => 'Code est requis',
    'Reset.MissingMethodUID' => 'Méthode UID requise pour la méthode de type de réinitialisation',
    'Reset.MissingRecaptchaCode' => 'Le code de vérification reCAPTCHA est requis',
    'Reset.MissingResetType' => 'Type de réinitialisation invalide',
    'Reset.MissingUsername' => 'Valeur est requise',
    'Reset.NotFound' => 'Réinitialiser introuvable',
    'Reset.PasswordResetForSubject' => '{idpDisplayName} demande de réinitialisation du mot de passe pour {name}',
    'Reset.PasswordResetSubject' => '{idpDisplayName} demande de réinitialisation du mot de passe',
    'Reset.RecaptchaFailedVerification' => 'reCAPTCHA a échoué la vérification',
    'Reset.SetDisableTimeError' => 'Impossible d\'enregistrer la réinitialisation avec disable_until.',
    'Reset.UnknownType' => 'Type de réinitialisation inconnu demandé',
    'Reset.UpdateFailure' => 'Impossible de mettre à jour la réinitialisation dans la base de données, e-mail non envoyé.',
    'Reset.UpdateTypeError' => 'Impossible de mettre à jour le type de réinitialisation.',
    'Reset.UserNotFound' => 'Utilisateur introuvable',
    'Utils.InvalidEmail' => 'Adresse email invalide fournie',
    'Utils.RecaptchaVerifyFailure' => 'Impossible de vérifier reCAPTCHA',
    'Zxcvbn.LowScore' => 'Le mot de passe n\'a pas atteint la valeur minimale de {minScore}Essayez d\'ajouter des mots, mais évitez les expressions courantes.',
];
