<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth.MissingClientID' => '',
    'Method.AlreadyExists' => '',
    'Method.CodeExpired' => '',
    'Method.CodeMissing' => '',
    'Method.EmailReuseError' => '',
    'Method.InvalidCode' => '',
    'Method.InvalidEmail' => '',
    'Method.MissingValue' => '',
    'Method.NotFound' => '',
    'Method.PersonnelError' => '',
    'Method.TooManyFailures' => '',
    'Mfa.AlreadyExists' => '',
    'Mfa.InvalidCode' => '',
    'Mfa.MissingValue' => '',
    'Mfa.RateLimitFailure' => '',
    'Mfa.RecordNotFound' => '',
    'Mfa.TypeMissing' => '',
    'Mfa.UpdateFailure' => '',
    'Mfa.VerifyFailure' => '',
    'Password.Breached' => '',
    'Password.DisallowedContent' => '',
    'Password.MissingPassword' => '',
    'Password.PasswordReuse' => '',
    'Password.PublicPasswordUsed' => '',
    'Password.TooLong' => '',
    'Password.TooShort' => '',
    'Password.TooWeak' => '',
    'Password.UpdateError' => '',
    'Password.UpdateFailure' => '',
    'Reset.CannotEnable' => '',
    'Reset.CreateFailure' => '',
    'Reset.IncrementAttemptsError' => '',
    'Reset.InvalidCode' => '',
    'Reset.MissingClientID' => '',
    'Reset.MissingCode' => '',
    'Reset.MissingMethodUID' => '',
    'Reset.MissingRecaptchaCode' => '',
    'Reset.MissingResetType' => '',
    'Reset.MissingUsername' => '',
    'Reset.NotFound' => '',
    'Reset.PasswordResetForSubject' => '',
    'Reset.PasswordResetSubject' => '',
    'Reset.RecaptchaFailedVerification' => '',
    'Reset.SetDisableTimeError' => '',
    'Reset.UnknownType' => '',
    'Reset.UpdateFailure' => '',
    'Reset.UpdateTypeError' => '',
    'Reset.UserNotFound' => '',
    'Utils.InvalidEmail' => '',
    'Utils.RecaptchaVerifyFailure' => '',
    'Zxcvbn.LowScore' => '',
];
