<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Jeton d\'authentification',
    'Access Token Expiration' => 'Expiration jeton d\'accès',
    'Attempts' => 'Tentatives',
    'Auth Type' => 'Type d\'Auth',
    'Code' => 'Code',
    'Created' => 'Créé',
    'Deleted At' => 'Supprimé à',
    'Details' => 'Plus d\'informations',
    'Disable Until' => 'Désactiver jusqu\'au',
    'Email' => 'Email',
    'Employee ID' => 'Identifiant d\'employé',
    'Expires' => 'Expiré',
    'First Name' => 'Nom',
    'Hide' => 'Masquer',
    'ID' => 'ID',
    'Idp Username' => 'Nom d\'utilisateur IdP',
    'Last Name' => 'Nom De Famille',
    'Topic' => 'Une discussion',
    'Type' => 'Type',
    'Uid' => 'UID',
    'User ID' => 'ID d\'utilisateur ',
    'Uuid' => 'UUID',
    'Value' => 'Valeur',
    'Verification Attempts' => 'Questions de vérification',
    'Verification Code' => 'Code de Vérification',
    'Verification Expires' => 'Echec de la vérification',
    'Verified' => 'Vérifié',
];
