<?php
namespace frontend\controllers;

use frontend\components\BaseRestController;
use Sil\Idp\IdBroker\Client\IdBrokerClient;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;

class MfaController extends BaseRestController
{

    /**
     * @var IdBrokerClient
     */
    public $idBrokerClient;

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ]
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $config = \Yii::$app->params['mfa'];
        $this->idBrokerClient = new IdBrokerClient($config['idBrokerBaseUrl'], $config['accessToken']);
    }

    public function actionIndex()
    {

        return $this->getMfaList();
    }

    public function actionCreate()
    {
        $type = \Yii::$app->request->getBodyParam('type');
        if ($type === null) {
            throw new BadRequestHttpException('Type is required');
        }

        return $this->idBrokerClient->mfaCreate(\Yii::$app->user->identity->employee_id, $type);
    }

    public function actionDelete($mfaId)
    {
        $mfaList = $this->getMfaList();
        foreach ($mfaList as $mfa) {
            if ($mfa['id'] === $mfaId) {
                return $this->idBrokerClient->mfaDelete($mfaId);
            }
        }

        throw new NotFoundHttpException();
    }

    public function actionVerify($mfaId)
    {
        $value = \Yii::$app->request->getBodyParam('value');
        if ($value === null) {
            throw new BadRequestHttpException('Value is required');
        }

        $mfaList = $this->getMfaList();
        foreach ($mfaList as $mfa) {
            if ($mfa['id'] === $mfaId) {
                return $this->idBrokerClient->mfaVerify($mfaId, $value);
            }
        }

        throw new NotFoundHttpException();
    }

    private function getMfaList()
    {
        return $this->idBrokerClient->mfaList(\Yii::$app->user->identity->employee_id);
    }

}