<?php
return [
    [
        'first_name' => 'First',
        'last_name' => 'Last',
        'email' => 'first_last@organization.org',
        'employee_id' => '111111',
        'username' => 'first_last',
        'manager_email' => 'supervisor@domain.org',
        'spouse_email' => 'spouse@domain.org',
        'do_not_disclose' => false,
    ],
    [
        'first_name' => 'First2',
        'last_name' => 'Last2',
        'email' => 'first_last2@domain.com',
        'employee_id' => '222222',
        'username' => 'first2_last2',
        'manager_email' => null,
        'spouse_email' => null,
        'do_not_disclose' => false,
    ],
    [
        'first_name' => 'First3',
        'last_name' => 'Last3',
        'email' => 'first_last3@domain.com',
        'employee_id' => '333333',
        'username' => 'first3_last3',
        'manager_email' => null,
        'spouse_email' => null,
        'do_not_disclose' => false,
    ],
    [
        'first_name' => 'First4',
        'last_name' => 'Last4',
        'email' => 'first_last4@example.com',
        'employee_id' => '444444',
        'username' => 'first4_last4',
        'manager_email' => 'supervisor4@example.com',
        'spouse_email' => 'spouse4@example.com',
        'do_not_disclose' => false,
    ],
];
